providers = ["node"]

[variables]
NIXPACKS_PATH = "/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]
