providers = ["node"]

[variables]
NIXPACKS_PATH = "/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx vite build"]

[start]
cmd = "npx serve -s dist -l $PORT"
