providers = ["node"]

[variables]
NIXPACKS_PATH = "/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = ["npm install", "npx tsc"]

[start]
cmd = "node dist/index.js"
