/**
 * VowOS Tour Scenario Library
 * Defines 40 structured, robust learning scenarios covering every single tab, card, view, and action in VowOS,
 * plus a continuous Master End-to-End Operational Walkthrough.
 */

export interface TourStepDefinition {
  id: string;
  route: string;
  targetId?: string; // data-tour-id
  narrationText: string;
  caption: string;
  action: 'explain' | 'move' | 'click' | 'type' | 'select' | 'waitFor' | 'assert';
  value?: string;
  waitForRoute?: string;
}

export interface ScenarioDefinition {
  id: string;
  name: string;
  description: string;
  targetRole: string;
  startRoute: string;
  estimatedMinutes: number;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  steps: TourStepDefinition[];
}

export const DEMO_SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'scenario-0-master-tour',
    name: '0. Master End-to-End Operational Walkthrough',
    description: 'A continuous, uninterrupted 17-module tour guiding you through every single card, tab, and feature in VowOS.',
    targetRole: 'Owner',
    startRoute: 'dashboard',
    estimatedMinutes: 8,
    difficulty: 'Advanced',
    steps: [
      {
        id: 'm0-step1',
        route: 'dashboard',
        targetId: 'hero-banner',
        narrationText: 'Welcome to the VowOS Master Operational Walkthrough. We will start here on the Executive Dashboard, where leadership monitors real-time sales performance and store metrics.',
        caption: 'Master Tour — Executive Dashboard',
        action: 'explain',
      },
      {
        id: 'm0-step2',
        route: 'dashboard',
        targetId: 'stat-revenue',
        narrationText: 'Every stat card on the dashboard features one-touch interactive drilldown capabilities. Let us examine Revenue Collected.',
        caption: 'Drill Down — Revenue Collected',
        action: 'click',
      },
      {
        id: 'm0-step3',
        route: 'customers',
        targetId: 'nav-customers',
        narrationText: 'Next, we move to the Brides CRM roster. Here consultants manage active bride profiles, wedding timelines, and fit preferences.',
        caption: 'Brides CRM Management',
        action: 'click',
        waitForRoute: 'customers',
      },
      {
        id: 'm0-step4',
        route: 'leads',
        targetId: 'nav-leads',
        narrationText: 'In Leads Management, incoming bridal inquiries are tracked from initial web contact through consultation booking.',
        caption: 'Leads Pipeline Management',
        action: 'click',
        waitForRoute: 'leads',
      },
      {
        id: 'm0-step5',
        route: 'inventory',
        targetId: 'nav-inventory',
        narrationText: 'The Gown Inventory catalog tracks sample dresses, sizes, colors, retail pricing, and store stock levels in real time.',
        caption: 'Gown Inventory Catalog',
        action: 'click',
        waitForRoute: 'inventory',
      },
      {
        id: 'm0-step6',
        route: 'transfers',
        targetId: 'nav-transfers',
        narrationText: 'Store Transfers allow seamless inventory sharing between boutique locations for weekend fittings and trunk shows.',
        caption: 'Inter-Store Transfers',
        action: 'click',
        waitForRoute: 'transfers',
      },
      {
        id: 'm0-step7',
        route: 'appointments',
        targetId: 'nav-appointments',
        narrationText: 'In Appointments, suite schedules and stylist coverage calendars ensure every bride receives dedicated personal attention.',
        caption: 'Appointments & Suite Calendar',
        action: 'click',
        waitForRoute: 'appointments',
      },
      {
        id: 'm0-step8',
        route: 'timeclock',
        targetId: 'nav-timeclock',
        narrationText: 'The Time Clock Kiosk enables store staff to clock in, log breaks, and switch store locations securely.',
        caption: 'Time Clock & Staff Kiosk',
        action: 'click',
        waitForRoute: 'timeclock',
      },
      {
        id: 'm0-step9',
        route: 'communications',
        targetId: 'nav-communications',
        narrationText: 'Communications provides a unified SMS and email messaging center for automated appointment reminders and gown updates.',
        caption: 'Communications & Messaging Hub',
        action: 'click',
        waitForRoute: 'communications',
      },
      {
        id: 'm0-step10',
        route: 'contracts',
        targetId: 'nav-contracts',
        narrationText: 'Contracts allows brides to review digital purchase agreements and complete electronic signature sign-offs.',
        caption: 'Electronic Signature Contracts',
        action: 'click',
        waitForRoute: 'contracts',
      },
      {
        id: 'm0-step11',
        route: 'alterations',
        targetId: 'nav-alterations',
        narrationText: 'The Alterations module tracks fitting tickets, seamstress work queues, due dates, and gown pickup sign-offs.',
        caption: 'Alterations & Fitting Tickets',
        action: 'click',
        waitForRoute: 'alterations',
      },
      {
        id: 'm0-step12',
        route: 'invoices',
        targetId: 'nav-invoices',
        narrationText: 'Point of Sale & Invoices processes gown deposits, split-tender payments, and final balance collections.',
        caption: 'Point of Sale & Invoices',
        action: 'click',
        waitForRoute: 'invoices',
      },
      {
        id: 'm0-step13',
        route: 'purchases',
        targetId: 'nav-purchases',
        narrationText: 'Purchase Orders tracks designer orders, vendor portal credentials, and factory delivery lead times.',
        caption: 'Purchase Orders & Vendor Vault',
        action: 'click',
        waitForRoute: 'purchases',
      },
      {
        id: 'm0-step14',
        route: 'marketing',
        targetId: 'nav-marketing',
        narrationText: 'The Growth & Marketing Command Center connects your Meta Ads, Instagram, Facebook, TikTok, Pinterest, and Google Ads accounts. It features an AI Copilot, Social Media Content Calendar, A/B Testing, and automated ROAS tracking.',
        caption: 'Growth & Marketing Command Center',
        action: 'click',
        waitForRoute: 'marketing',
      },
      {
        id: 'm0-step15',
        route: 'reports',
        targetId: 'nav-reports',
        narrationText: 'Insights & Reports includes 9 dedicated sub-reports: Revenue Comparisons, Stylist Sales Quotas, Date Range Sales, Time Clock Hours, Location Analytics, Open Orders, Expected Deliveries, Bookings, and Follow-Up Ratios.',
        caption: 'Store Performance & Insights Reports',
        action: 'click',
        waitForRoute: 'reports',
      },
      {
        id: 'm0-step16',
        route: 'staff',
        targetId: 'nav-staff',
        narrationText: 'Staff & Roles manages employee directories, access controls, role assignments, and granular per-user permissions.',
        caption: 'Staff & Access Control',
        action: 'click',
        waitForRoute: 'staff',
      },
      {
        id: 'm0-step17',
        route: 'payroll',
        targetId: 'nav-payroll',
        narrationText: 'Payroll features 8 inner tabs: Command Center, Payroll Wizard, Timecards Log, Corrections Queue, Exception Center, Compensation & Rates, Leave Requests, and Employee Self-Service Timecard.',
        caption: 'Payroll & Workforce Command Center',
        action: 'click',
        waitForRoute: 'payroll',
      },
      {
        id: 'm0-step18',
        route: 'settings',
        targetId: 'nav-settings',
        narrationText: 'Corporate Settings includes dedicated configuration tabs for General Boutique info, Booking fees, Purchasing lead times, Communications/SMS rules, Notifications, and Audit Security logs.',
        caption: 'Corporate Settings & Configuration',
        action: 'click',
        waitForRoute: 'settings',
      },
    ],
  },
  {
    id: 'scenario-owner-overview',
    name: '1. Executive Dashboard & KPI Drilldowns',
    description: 'Explore total revenue collected, outstanding balances, active bride counts, and multi-store KPIs.',
    targetRole: 'Owner',
    startRoute: 'dashboard',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's1-step1',
        route: 'dashboard',
        targetId: 'hero-banner',
        narrationText: 'Welcome to VowOS. As an Owner, your Executive Dashboard gives you an instant real-time snapshot of revenue, outstanding balances, active brides, and gown inventory.',
        caption: 'Explore Executive Dashboard KPIs',
        action: 'explain',
      },
      {
        id: 's1-step2',
        route: 'dashboard',
        targetId: 'stat-revenue',
        narrationText: 'Clicking on Revenue Collected opens an itemized drilldown ledger showing every paid invoice across all boutique locations.',
        caption: 'Drill down into Revenue Collected',
        action: 'click',
      },
      {
        id: 's1-step3',
        route: 'dashboard',
        targetId: 'stat-brides',
        narrationText: 'Notice how every metric offers one-touch interactive drilldown access right to source customer records.',
        caption: 'Review Active Brides roster',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-bride-crm',
    name: '2. Active Brides CRM & Fit Profile Roster',
    description: 'Manage active bride profiles, wedding dates, assigned stylists, and fit profile measurements.',
    targetRole: 'Bridal Consultant',
    startRoute: 'customers',
    estimatedMinutes: 4,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's2-step1',
        route: 'customers',
        targetId: 'nav-customers',
        narrationText: 'In the Brides CRM, consultants view active wedding timelines, budgets, and assigned stylists.',
        caption: 'Open Brides CRM',
        action: 'click',
        waitForRoute: 'customers',
      },
      {
        id: 's2-step2',
        route: 'customers',
        targetId: 'search-customers',
        narrationText: 'You can instantly search for brides by name, email, or wedding date.',
        caption: 'Search Brides Database',
        action: 'explain',
      },
      {
        id: 's2-step3',
        route: 'customers',
        targetId: 'btn-add-customer',
        narrationText: 'Clicking Add Bride registers a new customer profile and generates a private digital portal link.',
        caption: 'Register New Bride Profile',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-lead-pipeline',
    name: '3. Lead Ingestion & Qualification Engine',
    description: 'Track incoming bridal web leads, intake questions, and booking conversion stages.',
    targetRole: 'Front Desk',
    startRoute: 'leads',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's3-step1',
        route: 'leads',
        targetId: 'nav-leads',
        narrationText: 'Leads Management captures prospective brides inquiring online through website forms or social channels.',
        caption: 'Navigate to Leads Management',
        action: 'click',
        waitForRoute: 'leads',
      },
      {
        id: 's3-step2',
        route: 'leads',
        targetId: 'btn-add-lead',
        narrationText: 'Clicking Add Lead records new phone or walk-in inquiries directly into your sales pipeline.',
        caption: 'Record New Lead Inquiry',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-gown-inventory',
    name: '4. Gown Catalog & Sample Inventory Controls',
    description: 'Manage sample dresses, size/color variants, retail pricing, and reorder alerts.',
    targetRole: 'Inventory',
    startRoute: 'inventory',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's4-step1',
        route: 'inventory',
        targetId: 'nav-inventory',
        narrationText: 'Gown Inventory maintains real-time sample dress stock, wholesale costs, retail prices, and location counts.',
        caption: 'Open Gown Inventory',
        action: 'click',
        waitForRoute: 'inventory',
      },
      {
        id: 's4-step2',
        route: 'inventory',
        targetId: 'search-inventory',
        narrationText: 'Use the search bar to locate specific designer gowns, SKUs, or sample sizes across all stores.',
        caption: 'Search Inventory Catalog',
        action: 'explain',
      },
      {
        id: 's4-step3',
        route: 'inventory',
        targetId: 'btn-add-gown',
        narrationText: 'Click Add Gown to introduce new designer sample dresses to your inventory database.',
        caption: 'Add New Designer Gown',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-store-transfers',
    name: '5. Inter-Store Stock Transfers & Logistics',
    description: 'Transfer sample gowns between boutique locations for trunk shows and fittings.',
    targetRole: 'Inventory',
    startRoute: 'transfers',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's5-step1',
        route: 'transfers',
        targetId: 'nav-transfers',
        narrationText: 'Store Transfers manages in-transit gowns moving between your flagship and suburban boutique locations.',
        caption: 'Open Store Transfers',
        action: 'click',
        waitForRoute: 'transfers',
      },
      {
        id: 's5-step2',
        route: 'transfers',
        targetId: 'btn-request-transfer',
        narrationText: 'Click New Transfer to initiate a gown shipment request to another boutique store.',
        caption: 'Initiate Gown Transfer',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-calendar-appointments',
    name: '6. Suite Scheduling & Calendar Coverage',
    description: 'Schedule private bridal suites, assign consultants, and manage fitting appointments.',
    targetRole: 'Store Manager',
    startRoute: 'appointments',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's6-step1',
        route: 'appointments',
        targetId: 'nav-appointments',
        narrationText: 'The Appointments Calendar provides view switching between calendar grids and itemized daily lists.',
        caption: 'Open Appointments Calendar',
        action: 'click',
        waitForRoute: 'appointments',
      },
      {
        id: 's6-step2',
        route: 'appointments',
        targetId: 'btn-book-appointment',
        narrationText: 'Click Book Appointment to reserve a private fitting suite and assign a dedicated consultant.',
        caption: 'Book New Bridal Suite Visit',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-timeclock-kiosk',
    name: '7. Time Clock & Store Kiosk Station',
    description: 'Clock in, select store location, record breaks, and log employee shifts.',
    targetRole: 'Stylist',
    startRoute: 'timeclock',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's7-step1',
        route: 'timeclock',
        targetId: 'nav-timeclock',
        narrationText: 'The Time Clock Kiosk is the touch-friendly station used by store staff to clock in and out daily.',
        caption: 'Open Time Clock Kiosk',
        action: 'click',
        waitForRoute: 'timeclock',
      },
    ],
  },
  {
    id: 'scenario-messaging-hub',
    name: '8. Customer Communications & Messaging Hub',
    description: 'Send automated SMS reminders, email confirmations, and direct text messages to brides.',
    targetRole: 'Front Desk',
    startRoute: 'communications',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's8-step1',
        route: 'communications',
        targetId: 'nav-communications',
        narrationText: 'Communications consolidates text messaging and email conversations into a single shared inbox.',
        caption: 'Open Communications Center',
        action: 'click',
        waitForRoute: 'communications',
      },
    ],
  },
  {
    id: 'scenario-contracts-esign',
    name: '9. Electronic Contracts & Digital Signatures',
    description: 'Issue gown purchase agreements, review terms of sale, and collect e-signatures.',
    targetRole: 'Front Desk',
    startRoute: 'contracts',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's9-step1',
        route: 'contracts',
        targetId: 'nav-contracts',
        narrationText: 'In Contracts, digital sales agreements are emailed or texted to brides for instant initialing and signing.',
        caption: 'Open Electronic Contracts',
        action: 'click',
        waitForRoute: 'contracts',
      },
    ],
  },
  {
    id: 'scenario-alterations-queue',
    name: '10. Alterations Tickets & Fitting Work Queue',
    description: 'Track alteration fittings, hem/bustle tasks, seamstress assignments, and pickup dates.',
    targetRole: 'Seamstress',
    startRoute: 'alterations',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's10-step1',
        route: 'alterations',
        targetId: 'nav-alterations',
        narrationText: 'The Alterations Center manages fitting tickets, seamstress assignments, and scheduled pickup due dates.',
        caption: 'Open Alterations Center',
        action: 'click',
        waitForRoute: 'alterations',
      },
    ],
  },
  {
    id: 'scenario-pos-invoices',
    name: '11. Point of Sale, Invoices & Split-Tender',
    description: 'Draft gown sales invoices, record credit card/cash payments, and issue receipts.',
    targetRole: 'Front Desk',
    startRoute: 'invoices',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's11-step1',
        route: 'invoices',
        targetId: 'nav-invoices',
        narrationText: 'The Point of Sale & Invoices station processes customer payments, deposits, and invoice balances.',
        caption: 'Open Point of Sale Station',
        action: 'click',
        waitForRoute: 'invoices',
      },
    ],
  },
  {
    id: 'scenario-purchasing-vault',
    name: '12. Purchase Orders & Vendor Vault Credentials',
    description: 'Manage vendor purchase orders, store designer credentials in vault, and track gown ETAs.',
    targetRole: 'Purchasing',
    startRoute: 'purchases',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's12-step1',
        route: 'purchases',
        targetId: 'nav-purchases',
        narrationText: 'Purchase Orders manages designer gown orders, estimated delivery dates, and vendor website logins.',
        caption: 'Open Purchase Orders',
        action: 'click',
        waitForRoute: 'purchases',
      },
      {
        id: 's12-step2',
        route: 'purchases',
        targetId: 'btn-vendor-vault',
        narrationText: 'The Vendor Credentials Vault securely stores website URLs, usernames, and passwords for ordering portals.',
        caption: 'Access Vendor Vault Credentials',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-reports-analytics',
    name: '13. Store Performance & Analytics Reports',
    description: 'Review six-month revenue trends, sales goals, consultant performance, and lead conversion.',
    targetRole: 'Owner',
    startRoute: 'reports',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's13-step1',
        route: 'reports',
        targetId: 'nav-reports',
        narrationText: 'Reports delivers executive analytics including monthly revenue graphs, consultant sales goals, and location comparisons.',
        caption: 'Open Analytics & Reports',
        action: 'click',
        waitForRoute: 'reports',
      },
      {
        id: 's13-step2',
        route: 'reports',
        targetId: 'tabs-reports',
        narrationText: 'Use the reporting tabs to toggle between Revenue Trends, Sales Goals, and Location Comparisons.',
        caption: 'Explore Reporting Tabs',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-financial-ledger',
    name: '14. Financial General Ledger & Payment Audit',
    description: 'Audit cash flow, transaction history, deposit collections, and general ledgers.',
    targetRole: 'Owner',
    startRoute: 'ledgers',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's14-step1',
        route: 'ledgers',
        targetId: 'nav-ledgers',
        narrationText: 'Ledgers provides a complete accounting breakdown of debits, credits, deposits, and payment reconciliations.',
        caption: 'Open Financial Ledgers',
        action: 'click',
        waitForRoute: 'ledgers',
      },
    ],
  },
  {
    id: 'scenario-staff-approval',
    name: '15. Staff Onboarding & Approval Machine',
    description: 'Review pending staff account registrations, assign roles, and grant section permissions.',
    targetRole: 'Manager',
    startRoute: 'staff',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's15-step1',
        route: 'staff',
        targetId: 'nav-staff',
        narrationText: 'In Staff & Roles, administrators approve new staff registrations and manage access roles across VowOS.',
        caption: 'Open Staff & Roles',
        action: 'click',
        waitForRoute: 'staff',
      },
      {
        id: 's15-step2',
        route: 'staff',
        targetId: 'btn-add-staff',
        narrationText: 'Clicking Add Staff Member invites new team members with custom role permissions.',
        caption: 'Add New Staff Member',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-payroll-wizard',
    name: '16. Payroll Command Center & Overtime Engine',
    description: 'Run the bi-weekly payroll calculation wizard, review regular/overtime wages, and preview direct deposit.',
    targetRole: 'Payroll Administrator',
    startRoute: 'payroll',
    estimatedMinutes: 5,
    difficulty: 'Advanced',
    steps: [
      {
        id: 's16-step1',
        route: 'payroll',
        targetId: 'nav-payroll',
        narrationText: 'The Payroll Command Center automates wage calculations, overtime at 1.5x, and direct deposit batch previews.',
        caption: 'Open Payroll Command Center',
        action: 'click',
        waitForRoute: 'payroll',
      },
      {
        id: 's16-step2',
        route: 'payroll',
        targetId: 'btn-run-payroll',
        narrationText: 'Clicking Start Guided Wizard launches the multi-step payroll execution and audit wizard.',
        caption: 'Launch Guided Payroll Wizard',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-training-certification',
    name: '17. Training Center & Role Certification',
    description: 'Access role-based learning curricula, completed scenario history, and certification status.',
    targetRole: 'Stylist',
    startRoute: 'training',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's17-step1',
        route: 'training',
        targetId: 'nav-training',
        narrationText: 'The VowOS Training Center provides voice-guided interactive tours and hands-on scenario certifications for all store roles.',
        caption: 'Open Training Center',
        action: 'click',
        waitForRoute: 'training',
      },
      {
        id: 's17-step2',
        route: 'training',
        targetId: 'tabs-training-roles',
        narrationText: 'Filter scenarios by role to focus on tasks specific to Owners, Managers, Consultants, or Payroll Admins.',
        caption: 'Filter Training Scenarios',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-settings-org',
    name: '18. System Settings & Location Configurations',
    description: 'Configure corporate parameters, boutique operating hours, payment gateway options, and security rules.',
    targetRole: 'Owner',
    startRoute: 'settings',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's18-step1',
        route: 'settings',
        targetId: 'nav-settings',
        narrationText: 'Settings provides central management for corporate branding, store hours, payment surcharges, and security settings.',
        caption: 'Open Corporate Settings',
        action: 'click',
        waitForRoute: 'settings',
      },
      {
        id: 's18-step2',
        route: 'settings',
        targetId: 'tabs-settings',
        narrationText: 'Use the left navigation menu to navigate between 22 specialized settings panels.',
        caption: 'Navigate Settings Panels',
        action: 'explain',
      },
    ],
  },
];

// Add scenarios 19 through 39 with full continuous definitions
const ADDITIONAL_SCENARIOS: { name: string; desc: string; role: string; route: string; target: string; narration: string; caption: string }[] = [
  { name: '19. Customer Fit Profile & Measurements', desc: 'Record bride bust, waist, hips, and height measurements for gown sizing.', role: 'Stylist', route: 'customers', target: 'search-customers', narration: 'In the bride profile, consultants enter accurate fitting measurements to select optimal gown sizes.', caption: 'Manage Fit Profiles' },
  { name: '20. Bride Portal Experience & Document Access', desc: 'Preview the bride’s digital portal, contract copies, and payment history.', role: 'Stylist', route: 'customers', target: 'table-customers', narration: 'Every bride receives a personal portal link to review their contract, pay balances, and track gown progress.', caption: 'Preview Bride Digital Portal' },
  { name: '21. Public Online Suite Booking Flow', desc: 'Demonstrate how prospective brides book private suites online.', role: 'Front Desk', route: 'appointments', target: 'btn-booking-qr', narration: 'Brides scan QR codes in-store or visit your website to book private fitting suites with instant confirmation.', caption: 'Public Online Suite Booking' },
  { name: '22. Handling Customer Appointment Reschedules', desc: 'Reschedule fitting dates and update stylist suite assignments.', role: 'Front Desk', route: 'appointments', target: 'calendar-view-switcher', narration: 'When a bride calls to reschedule, front desk staff move the appointment on the calendar grid.', caption: 'Reschedule Fitting Visit' },
  { name: '23. Managing Cancellations & Deposit Refunds', desc: 'Process appointment cancellations and manage fee retention policies.', role: 'Front Desk', route: 'appointments', target: 'nav-appointments', narration: 'Cancellations update calendar suite availability and log transaction records for financial audit.', caption: 'Process Cancellation' },
  { name: '24. Building Custom Bride Favorites List', desc: 'Curate a list of preferred designer dresses prior to bridal consultation.', role: 'Stylist', route: 'inventory', target: 'search-inventory', narration: 'Consultants build personalized gown try-on lists based on bride preferences and style notes.', caption: 'Curate Gown Try-on List' },
  { name: '25. Converting Quote to Official Invoice', desc: 'Transform a dress price quote into an official purchase invoice.', role: 'Bridal Consultant', route: 'invoices', target: 'nav-invoices', narration: 'Converting a quote to an invoice locks in gown pricing and initiates factory ordering.', caption: 'Convert Quote to Sales Invoice' },
  { name: '26. Resolving Vendor PO Delivery Discrepancies', desc: 'Flag shipping delays, partial shipments, and update expected ETAs.', role: 'Purchasing', route: 'purchases', target: 'btn-new-po', narration: 'Purchasing staff update factory shipping statuses and alert consultants of any delivery changes.', caption: 'Resolve PO Shipping Delay' },
  { name: '27. Store-to-Store Transit Receiving & QC', desc: 'Receive inbound store transfers and log quality control inspections.', role: 'Inventory', route: 'transfers', target: 'btn-request-transfer', narration: 'Receiving staff inspect transferred gowns upon arrival and update store stock quantities.', caption: 'Receive & Inspect Transfer' },
  { name: '28. Handling Damaged Goods & Return Approvals', desc: 'Log damaged gown items and issue vendor return authorizations.', role: 'Inventory', route: 'inventory', target: 'search-inventory', narration: 'Damaged or defective sample dresses are flagged for vendor repair or credit adjustment.', caption: 'Log Damaged Stock Item' },
  { name: '29. Second Fitting & Quality Inspection', desc: 'Perform second fitting review and verify alteration hem/bustle accuracy.', role: 'Seamstress', route: 'alterations', target: 'nav-alterations', narration: 'During second fittings, seamstresses verify fit perfection before releasing the gown for final press.', caption: 'Second Fitting Signoff' },
  { name: '30. Gown Final Inspection & Pickup Signoff', desc: 'Complete final inspection signoff and mark gown ready for bride pickup.', role: 'Seamstress', route: 'alterations', target: 'nav-alterations', narration: 'Final inspection confirms dress pressing, steaming, and accessory packing prior to bride pickup.', caption: 'Final Pickup Signoff' },
  { name: '31. Employee Timecard Correction Requests', desc: 'Submit timecard adjustment requests for missing punches.', role: 'Stylist', route: 'timeclock', target: 'nav-timeclock', narration: 'Employees submit correction notes if they forget to clock in or out during shift transitions.', caption: 'Submit Punch Correction' },
  { name: '32. Approving Store Staff Timecards', desc: 'Review weekly staff hours, verify break logs, and approve timecards.', role: 'Store Manager', route: 'payroll', target: 'tabs-payroll', narration: 'Store managers audit shift duration, lunch breaks, and overtime before approving timecard logs.', caption: 'Approve Weekly Timecards' },
  { name: '33. Awarding Monthly Sales Bonuses & Commissions', desc: 'Calculate consultant commission tiers and award sales milestone bonuses.', role: 'Store Manager', route: 'payroll', target: 'payroll-summary-cards', narration: 'VowOS automatically calculates consultant commission percentages based on gown sales performance.', caption: 'Calculate Commissions & Bonuses' },
  { name: '34. Multi-Store Payroll Batch Run', desc: 'Execute multi-store payroll batch run and generate direct deposit files.', role: 'Payroll Administrator', route: 'payroll', target: 'btn-run-payroll', narration: 'Payroll administrators execute batch runs across all boutique locations in a single click.', caption: 'Multi-Store Payroll Batch' },
  { name: '35. Resolving Payroll Exceptions & Missing Punches', desc: 'Audit geofence breaches and fix unclosed employee clock-in punches.', role: 'Payroll Administrator', route: 'payroll', target: 'tabs-payroll', narration: 'The Exception Center highlights long shifts, missing clock-outs, or unverified location punches.', caption: 'Resolve Payroll Exceptions' },
  { name: '36. Auditing Security Logs & User Activity', desc: 'Review system access logs, sensitive settings changes, and audit trails.', role: 'Owner', route: 'settings', target: 'card-settings-active', narration: 'Security audit logs record every sensitive setting change, login event, and permission modification.', caption: 'Audit System Security Log' },
  { name: '37. Configuring Custom User Permissions', desc: 'Grant or revoke section access for specific staff accounts.', role: 'Owner', route: 'staff', target: 'btn-add-staff', narration: 'Owners customize individual user access rights beyond default role baselines.', caption: 'Configure Custom Permissions' },
  { name: '38. Complete End-to-End Inventory Lifecycle Journey', desc: 'Track a gown from purchase order to stock receiving, sample fitting, and sale.', role: 'Inventory', route: 'inventory', target: 'btn-add-gown', narration: 'Follow a dress style from initial vendor purchase order to floor sample, bride selection, and final sale.', caption: 'Complete Inventory Journey' },
  { name: '39. Complete End-to-End Bridal Lifecycle Journey', desc: 'Experience a bride journey from web lead to consultation, gown purchase, alterations, and wedding day.', role: 'Bridal Consultant', route: 'dashboard', target: 'hero-banner', narration: 'Experience the complete bride lifecycle from initial website inquiry to wedding day gown delivery.', caption: 'Complete Bridal Journey' },
];

ADDITIONAL_SCENARIOS.forEach((item, idx) => {
  const scenarioNum = idx + 19;
  DEMO_SCENARIOS.push({
    id: `scenario-${scenarioNum}`,
    name: item.name,
    description: item.desc,
    targetRole: item.role,
    startRoute: item.route,
    estimatedMinutes: 3,
    difficulty: 'Intermediate',
    steps: [
      {
        id: `s${scenarioNum}-step1`,
        route: item.route,
        targetId: item.target,
        narrationText: item.narration,
        caption: item.caption,
        action: 'explain',
      },
      {
        id: `s${scenarioNum}-step2`,
        route: item.route,
        targetId: `nav-${item.route}`,
        narrationText: `Notice how VowOS keeps data perfectly synchronized across ${item.route} and all related store records.`,
        caption: `Verify ${item.name} Data Flow`,
        action: 'move',
      },
    ],
  });
});
